version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/standalone"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/bootstrap"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/coverage-scanner"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/runtime-dep"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/impl-classtransform"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gradle-plugin"
    schedule:
      interval: "daily"
