version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/Standalone"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/RuntimeDep"
    schedule:
      interval: "daily"
