name: standalone
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew :Standalone:build
      - name: Upload build JARs
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-jars
          path: Standalone/build/libs/*
  test-geyser:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download standalone JAR
        uses: actions/download-artifact@v3
        with:
          name: build-jars
      - name: Download Geyser
        run: curl -Lo Geyser-Standalone.jar https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone
      - name: Downgrade Geyser
        run: java -jar JavaDowngrader-Standalone-*.jar -i Geyser-Standalone.jar -o Geyser-Standalone-out.jar -v 8
