name: standalone
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew :Standalone:build
      - name: Upload build JARs
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-jars
          path: Standalone/build/libs/*
  test-geyser:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download standalone JAR
        uses: actions/download-artifact@v3
        with:
          name: build-jars
      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: zulu
      - name: Download Geyser
        run: curl -Lo Geyser-Standalone.jar https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone
      - name: Downgrade Geyser
        run: java -jar JavaDowngrader-Standalone-*.jar -i Geyser-Standalone.jar -o Geyser-Standalone-out.jar -v 8
  test-paper:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download standalone JAR
        uses: actions/download-artifact@v3
        with:
          name: build-jars
      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: zulu
      - name: Download Paperclip
        run: wget https://api.papermc.io/v2/projects/paper/versions/1.19.4/builds/536/downloads/paper-1.19.4-536.jar
      - name: Downgrade Paperclip
        run: java -jar JavaDowngrader-Standalone-*.jar -i paper-1.19.4-536.jar -o paperclip-downgraded.jar -v 8
      - name: Run Paperclip
        run: java -Dpaperclip.patchonly=true -cp paperclip-downgraded.jar io.papermc.paperclip.Paperclip
      - name: Downgrade libraries
        run: |
          find libraries -type f -name "*.jar" -exec java -jar JavaDowngrader-Standalone-*.jar -i '{}' -o '{}.downgraded' -v 8 -l libraries \;
          find libraries -type f -name "*.jar" -exec rm '{}' \;
          find libraries -type f -name "*.jar.downgraded" -exec sh -c 'mv "$1" "${1%.jar.downgraded}.jar"' \;
      - name: Downgrade Paper
        run: java -jar JavaDowngrader-Standalone-*.jar -i versions/1.19.4/paper-1.19.4.jar -o paper-downgraded.jar -v 8 -l libraries
