name: test-standalone
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  test-geyser:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download standalone
        uses: actions/download-artifact@v3
        with:
          name: JavaDowngrader-standalone
      - name: Download coverage scanner
        uses: actions/download-artifact@v3
        with:
          name: JavaDowngrader-coverage-scanner
      - name: Set up JDK 21
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 21
          distribution: zulu
      - name: Download Geyser
        run: curl -Lo Geyser-Standalone.jar https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone
      - name: Downgrade Geyser
        run: java -jar JavaDowngrader-Standalone-1.1.2-SNAPSHOT.jar -i Geyser-Standalone.jar -o Geyser-Standalone-out.jar -v 8
      - name: Generate coverage report
        run: java -jar coverage-scanner-1.1.2-SNAPSHOT.jar Geyser-Standalone-out.jar > coverage-geyser.txt
      - name: Upload coverage report
        uses: actions/upload-artifact@v2.3.1
        with:
          name: coverage-report
          path: coverage-geyser.txt
  test-paperclip:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download standalone
        uses: actions/download-artifact@v3
        with:
          name: JavaDowngrader-standalone
      - name: Download coverage scanner
        uses: actions/download-artifact@v3
        with:
          name: JavaDowngrader-coverage-scanner
      - name: Set up JDK 21
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 21
          distribution: zulu
      - name: Download Paperclip
        run: wget https://api.papermc.io/v2/projects/paper/versions/1.20.2/builds/240/downloads/paper-1.20.2-240.jar
      - name: Downgrade Paperclip
        run: java -jar JavaDowngrader-Standalone-1.1.2-SNAPSHOT.jar -i paper-1.20.2-240.jar -o paperclip-downgraded.jar -v 8
      - name: Generate coverage report
        run: java -jar coverage-scanner-1.1.2-SNAPSHOT.jar paperclip-downgraded.jar > coverage-paperclip.txt
      - name: Upload coverage report
        uses: actions/upload-artifact@v2.3.1
        with:
          name: coverage-report
          path: coverage-paperclip.txt
  test-spigot:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download standalone
        uses: actions/download-artifact@v3
        with:
          name: JavaDowngrader-standalone
      - name: Download coverage scanner
        uses: actions/download-artifact@v3
        with:
          name: JavaDowngrader-coverage-scanner
      - name: Set up JDK 21
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 21
          distribution: zulu
      - name: Build Spigot
        run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar
          7z x spigot-*.jar "META-INF/versions/spigot-*.jar"
      - name: Downgrade Spigot
        run: java -jar JavaDowngrader-Standalone-1.1.2-SNAPSHOT.jar -i META-INF/versions/spigot-*.jar -o spigot-downgraded.jar -v 8
      - name: Generate coverage report
        run: java -jar coverage-scanner-1.1.2-SNAPSHOT.jar spigot-downgraded.jar > coverage-spigot.txt
      - name: Upload coverage report
        uses: actions/upload-artifact@v2.3.1
        with:
          name: coverage-report
          path: coverage-spigot.txt
